### ISSUE TITLE
Custom filtering + custom watching

### ISSUE THREAD

**Issue by hsume2** [mixu/gluejs#1]
I would like to be able to apply custom filter on a per module basis. For example:

``` js
new Glue()
  .include('./core')
  .filter(new RegExp('.+\.handlebars'), function(data, render) {
    var template = Handlebars.precompile(data);
    return render(template);
  })
  .export('Core')
  .watch(function (err, txt) {
    fs.writeFile('./core.js', txt);
  });
```

`render` refers to the stock implementation which wraps everything inside a closure:

``` js
(function(){
...
})();
```

This will let me add preprocessing steps prior to concatenation. However, in order for this to work, I would also need to be able to exclude *.handlebars files from the output, but still be able to filter them into the output via preprocessing.

**Comment by mixu** [comment]
Thanks for the suggestion. This now has preliminary support, though the implementation is a bit different:

``` js
var Handlebars = require('handlebars');
var g = new Glue(),
    extensionRe = new RegExp('(.+)\.handlebars$');
g.include('./fixtures/mixed_content/')
  .handler(extensionRe, function(filepath, done) {

    var template = Handlebars.precompile(fs.readFileSync(filepath).toString());
    done(g.wrap(filepath.replace(extensionRe, '$1.js'), template));

  })
  .render(function(err, txt) {
    console.log(txt);
    done();
  });
```

In short, here's what's different:
- naming: handler() instead of filter() 
- the current implementation actually just gives you the file path rather than the content of the file
- to wrap code into the standard closure, call .wrap(filename, content) before returning the value (has to be an instance method since we make paths relative to the base path in the output)
- the content is returned as the first param to the done() callback to allow for async calls during the processing

I'm still figuring out what the best way to expose this is, but I figure this is a start...

**Comment by hsume2** [comment]
Excellent solution! Thanks so much :)
