### ISSUE TITLE
Transform/Transpiling seems to have disappeared in v2

### ISSUE THREAD

**Issue by svizzari** [mixu/gluejs#20]
Mentioned in README but seemingly absent in this build.

**Comment by svizzari** [comment]
@mixu Oh, I get it, `command` will do the job.  Looking forward to the current work to support multiple commands with regex maturing to a release :smile_cat:

**Comment by mixu** [comment]
That's right! It'll be back soon, once I get the `command` option to work flexibly enough (sorry about the delay!). I'll probably support a bunch of templating libraries directly, could you tell me more about your use case?

**Comment by svizzari** [comment]
Hey Mikito

At the moment, I'm just wanting to pipe source through [Square's ES6-module-compiler](https://github.com/square/es6-module-transpiler).  Possibly also Typescript, not sure about that right now.

**Comment by svizzari** [comment]
@mixu Just curious, how stable would you say your current implementation of command to support multiple operations is?

**Comment by mixu** [comment]
@svizzari it's done! Just released v2.1, see the readme.md section on "What's new in v2.1".

In short:
- CPU-intensive builds are much faster
- caching is more capable and enabled by default
- transformations are now supported; either by using browserify's transform modules (with which gluejs is now API-compatible) or via custom transform modules

I actually used your use case as a sample case while building this out, see https://github.com/mixu/gluejs/blob/glue2/test/command-integration/es6-module.js for an example of how you might integrate with Square's ES6 module compiler. Run like this: https://github.com/mixu/gluejs/blob/glue2/test/command-integration/Makefile

Since this is all new, let me know if you have comments.

**Comment by svizzari** [comment]
@mixu Fantastic! I look forward to trying this out :heart_eyes_cat:
